### ISSUE TITLE
Access gdrive using service account credentials

### ISSUE THREAD

**Issue by dv-rastogi** [fsspec/gdrivefs#29]
Is there any support for authentication using service account credentials in `gdrivefs`?

**Comment by martindurant** [comment]
gcsfs can do this, so you could have a look to see whether the credentials object created there, with gdrive scopes, would work here.

**Comment by AlbertDeFusco** [comment]
I checked at the pydata-google-auth level that when I set the env var `GOOGLE_APPLICATION_CREDENTIALS` to the path to a JSON containing my client credentials that it picked up the right information provided. I think it will work the same for drivefs provided that your service account scope contains at least one of

```python
scope_dict = {'full_control': 'https://www.googleapis.com/auth/drive',
              'read_only': 'https://www.googleapis.com/auth/drive.readonly'}
```

**Comment by martindurant** [comment]
I suppose this whole package could do with some cleaning and documentation, etc. I am glad it worked well for you, @AlbertDeFusco !
