### ISSUE TITLE
IOError for any file larger than 8 MB when using `put_file`

### ISSUE THREAD

**Issue by Koncopd** [fsspec/gdrivefs#33]
`gdfs.put_file("./pbmc3k.h5ad", "test.zarr/pbmc3k.h5ad")`

```
File ~\Apps\Miniconda3\envs\nbproject\lib\site-packages\fsspec\spec.py:818, in AbstractFileSystem.put_file(self, lpath, rpath, callback, **kwargs)
    816 while f1.tell() < size:
    817     data = f1.read(self.blocksize)
--> 818     segment_len = f2.write(data)
    819     callback.relative_update(segment_len)

File ~\Apps\Miniconda3\envs\nbproject\lib\site-packages\fsspec\spec.py:1491, in AbstractBufferedFile.write(self, data)
   1489 self.loc += out
   1490 if self.buffer.tell() >= self.blocksize:
-> 1491     self.flush()
   1492 return out

File ~\Apps\Miniconda3\envs\nbproject\lib\site-packages\fsspec\spec.py:1532, in AbstractBufferedFile.flush(self, force)
   1529         self.closed = True
   1530         raise
-> 1532 if self._upload_chunk(final=force) is not False:
   1533     self.offset += self.buffer.seek(0, 2)
   1534     self.buffer = io.BytesIO()

File c:\users\sergei.rybakov\projects\gdrivefs\gdrivefs\core.py:323, in GoogleDriveFile._upload_chunk(self, final)
    321 else:
    322     print(head)
--> 323     raise IOError
    324 return True

OSError: 
```
Only 8 MB of any larger file seems to be written

The response header is this
`{'content-type': 'text/plain; charset=utf-8', 'x-guploader-uploadid': 'ADPycduaxaTB7yWT7UfaP0PupuzS4l1YcH0zTlU0tuGvn4fVm-htDaw2faGi923TuPtEDW64fYmXoXjIOLFui3QOWOVj', 'range': 'bytes=0-8388607', 'x-range-md5': '88e4c1dfd5e74cc994d6b8a66f8cd72c', 'content-length': '0', 'date': 'Sun, 15 Jan 2023 22:10:29 GMT', 'server': 'UploadServer', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'status': '308'}`

**Comment by Koncopd** [comment]
Thx, i will try.

**Comment by martindurant** [comment]
Updated/simplified the diff. I successfully uploaded a file >8MB like this. There *should* be a test on what headers google gives back, but I don't know what.

**Comment by Koncopd** [comment]
No, unfortunately for me it is still not working. It goes through with the upload, but the destination in the google drive is empty for large files. Small files are there after upload.

**Comment by martindurant** [comment]
Did you try with my second edit? You must make sure to delete the previous versions of the files from aborted attempts (in the gdrive interface to be certain), because gdrive allows you to have multiple files with the same identical name.

**Comment by Koncopd** [comment]
Yes, i tried the second edit. Everything works fine except for one specific file. I deleted the previous version, yes, the folder is empty of these files.

**Comment by efiop** [comment]
Hey @Koncopd ,

Honorable mention, you might want to give https://github.com/iterative/pydrive2 a try. We provide a fsspec filesystem there https://github.com/iterative/pydrive2#fsspec-filesystem that we use in https://github.com/iterative/dvc

**Comment by martindurant** [comment]
I am happy to swap out the gdrive implementation. I can't remember, what might be missing from pydrive2?

**Comment by efiop** [comment]
@martindurant Unfortunately I don't really know :( Might be some auth options, but it's been a long time and I don't remember :( The main drawback of pydrive2.fs is that it is based on pydrive2 and not on raw api, and pydrive2 is a fork of obsoleted pydrive that is using an older google api version. We've been meaning to migrate it to the never version, but unfortunately don't have the capacity now and probably won't any time soon.

**Comment by Koncopd** [comment]
pydrive2.fs is not a proper fsspec filesystem implementation, no seek for files etc.

**Comment by Koncopd** [comment]
Maybe i will try to make some PRs to this repo to fix the issues, when i familiarize myself with the gdrive API.
